### ISSUE TITLE
`[no_std]` compatibility for standalone crates

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/libcrux#313]
E.g. for `libcrux-kem`, or in general where possible.

**Comment by franziskuskiefer** [comment]
@jschneider-bensch let's list the crates and what needs to get done.

**Comment by franziskuskiefer** [comment]
Assigning to @keks as part of the first iteration of a pure Rust libcrux #648.

**Comment by keks** [comment]
I made most crates no_std in #697. Some didn't work, though:

- sys/hacl: depends on `std::os`
- psq: uses std::time::SystemTime
- macros: is proc-macro, so shouldn't need to

The PSQ one might be solvable, but I think our chances for sys/hacl are not very good. But since we are already in the way to migrating to hacl-rs, that is temporary.

@franziskuskiefer if you don't have objections, I would close this as resolved.

**Comment by franziskuskiefer** [comment]
> * sys/hacl: depends on `std::os`

As you say, since this is for wrapping C code we don't care for the pure Rust version.

> * psq: uses std::time::SystemTime

Let's not put this in scope for the first pure Rust release and file a separate issue for time not being in core.

> * macros: is proc-macro, so shouldn't need to

Right, this is fine.

Let's file that psq issue and close this.
